.github/workflows/release.yaml

The sgxs generation and signing aspects of the encrypting proxy release haven't been ironed out, and perhaps won't be necessary, as we will decent client support at launch.

ci: remove encrypting-proxy from release

---

clients/go/go.mod
clients/go/signed_calls.go
clients/go/signed_calls_test.go
clients/js/package.json
clients/js/pnpm-lock.yaml
clients/js/src/signed_calls.ts
clients/js/test/signed_calls.spec.ts

Note: this PR does not change security, only aesthetics.
With:
```js
const call = {  from, to, gasPrice, gasLimit, value, data };
const leash = { nonce, blockHash, blockRange };
function signCall(call: EthCall, leash: Leash} {
return eip712SignTypedData({ ...call, leash });
}
```
Before:
```js
{
data: encode({ // may be encrypted using `callformat.encode({ format, body: data })`
...call,
leash,
signature: signCall(call, leash),
}))
// the gateway and runtime will permit the original call here, but they're ignored by the runtime, which may be conusing
}
```
After:
```js
{
...call,
data: {
signature: signCall(call, leash),
leash,
data: { body: call.data } // may be encrypted using `callformat.encode({ format, body: call.data})`
}
}
```
Both formats are generally sign-then-encrypt, but the …

Modify signed query format

---

Cargo.lock
runtime/Cargo.toml
runtime/src/lib.rs

runtime: prepare 0.1.3-testnet

---

clients/js/src/cipher.ts
clients/js/test/cipher.spec.ts
clients/js/test/compat.spec.ts
clients/js/test/utils.ts

This PR fixes some discrepancies between the client envelope format and the actual runtime format (mainly around cbor encoding).

clients/js: fix envelope format

---

clients/js/.gitignore
clients/js/.prettierignore
clients/js/README.md
clients/js/package.json
clients/js/pnpm-lock.yaml
clients/js/src/cipher.ts
clients/js/src/compat.ts
clients/js/src/index.ts
clients/js/src/signed_calls.ts

This PR inserts a default gas limit into transactions that don't have one, which avoids the confusing error message of `core: invalid call format: key manager failure: client session is not authenticated` which happens because gas estimation is not allowed.
With this change, if the gas limit is too low, the user will get an out of gas error message. The risk of this change is that the user will call a contract that uses `abort` (which is uncommon nowadays) and lose all of their unspent gas. We should advertise in the docs that `gasLimit` needs to be set (or y'know, allow gas estimation because hiding it is not actually stopping motivated attackers).
[Source for the 90_000](https://ethereum.org/en/developers/docs/apis/json-rpc/#eth_sendtransaction)

clients/js: apply default gas limit

---

clients/js/package.json
clients/js/src/cipher.ts
clients/js/src/compat.ts
clients/js/src/signed_calls.ts
clients/js/test/cipher.spec.ts
clients/js/test/compat.spec.ts

This PR:
* increases compatibility of this library with versions of ethers by limiting the required props to just those used by this library
* changes `inferRuntimePublicKeySource` to always use `chainId`, as MetaMask does not call web3 methods it does not know about
* fixes the `Plain` cipher body encoding, which somehow escaped notice.

clients/js: fix types

---

clients/js/package.json

https://www.npmjs.com/package/@oasisprotocol/sapphire-paratime doesn't link back to repo. It probably wants different link format: https://docs.npmjs.com/cli/v8/configuring-npm/package-json#repository

Fix repo link in package.json

---

integrations/hardhat/index.js
integrations/hardhat/package.json

When working with mixed environments (e.g. basic local hardhat node with `--network localhost` and sapphire) the extension breaks as it tries to wrap the local provider:
```bash
$ yarn hardhat run scripts/deploy.ts --network localhost
yarn run v1.22.19
warning package.json: No license field
$ /Users/***/Documents/Work/[***/hardhat/node_modules/.bin/hardhat](http://***/hardhat/node_modules/.bin/hardhat) run scripts/deploy.ts --network localhost
TypeError: Cannot destructure property 'defaultGateway' of 'index_js_1.NETWORKS[chainId]' as it is undefined.
at /Users/***/Documents/Work/[***/hardhat/node_modules/@oasisprotocol/sapphire-paratime/src/cipher.ts:276:24](http://***/hardhat/node_modules/@oasisprotocol/sapphire-paratime/src/cipher.ts:276:24)
at Generator.next (<anonymous>)
at …
```

Fixing broken extension when working on mixed chains (e.g. localhost and sapphire)

---

clients/js/package.json
clients/js/src/cipher.ts

Initializing the cipher wasn't sufficiently one-time. This PR fixes that and also #73. @pro-wh warned about this, but the fix wasn't good enough.

clients/js: only generate lazy cipher once

---

runtime/Cargo.lock
runtime/Cargo.toml
runtime/src/lib.rs

This bumps Oasis Core to 22.2.5, increases the heap size to 256 MiB and updates the Testnet trust root.

runtime: Bump Oasis SDK to 45367837bc74540253c8a943cd982583f698be3f

---

.github/workflows/release.yaml
clients/js/src/cipher.ts
clients/js/src/index.ts
examples/hardhat-boilerplate/README.md
examples/hardhat-boilerplate/frontend/src/components/Dapp.js
examples/hardhat-boilerplate/hardhat.config.js
examples/hardhat/hardhat.config.ts
examples/truffle/truffle-config.js
runtime/src/lib.rs

Introduction of another *localnet* chain ID `0x5afd` if `OASIS_UNSAFE_USE_LOCALNET_CHAIN` env variable is set targeted at dApp devs for testing on the local stack. The PR sets this variable for debug-insecure builds on CI and renames the orc file to `localnet-sapphire-paratime.orc`.
Related: https://github.com/oasisprotocol/oasis-web3-gateway/pull/348, https://github.com/oasisprotocol/emerald-paratime/pull/27

runtime: Add OASIS_UNSAFE_USE_LOCALNET_CHAINID env flag

---

clients/go/cipher.go
clients/go/cipher_test.go
clients/js/package.json
clients/js/src/cipher.ts
clients/js/test/cipher.spec.ts

v0.5.0 introduced a change wherein the success or failure of the call is exposed: `Ok(Encrypt(Ok(result)))` and `Err(error)`. This PR adds decoding of encrypted `Ok`s to the client libraries.

Decode encrypted Ok and plain Fail

---

runtime/Cargo.lock
runtime/Cargo.toml
runtime/src/lib.rs

This release contains a fix for a gas overestimation issue introduced in 0.5.1-testnet.

runtime: Bump Oasis SDK to 0.6.0 and prepare 0.5.2-testnet

---

contracts/contracts/EIP155Signer.sol
contracts/contracts/EthereumUtils.sol
contracts/contracts/RLPWriter.sol
contracts/contracts/tests/EIP155Tests.sol
contracts/contracts/tests/SigningTests.sol
contracts/package.json
contracts/test/eip155.ts
contracts/test/precompiles.ts
pnpm-lock.yaml

This allows contracts to sign and encode Ethereum compatible EIP-155 transactions.
As a follow-up to https://github.com/oasisprotocol/demo-voting/pull/9 where we should make this code commonly available in sapphire-contracts library.
Truffle tests are still intermittent with `callback` related errors (weeiird).
This will require publishing an updated sapphire-contracts NPM repo.
RLPWriter contract is MIT licensed from elsewhere, with (multiple) attributions in the file.
TODO:

contracts: Added EIP-155 signer and extended EthereumUtils

---

contracts/contracts/EthereumUtils.sol
contracts/contracts/opl/Endpoint.sol
contracts/package.json

Fixes #155 
Also, fixed minor warning when compiling EthereumUtils.sol, it will no-longer warn about an unused return parameter.
Celer-IM documentation for MessageBus addresses are:
- https://im-docs.celer.network/developer/contract-addresses-and-rpc-info
Unrelated:
- There is still an intermittent failure in the Truffle CI tests using sapphire-dev. These will be addressed in another ticket/pr.

contracts: Update Celer MessageBus address for Sapphire Mainnet

---

.github/workflows/ci-lint.yaml
.github/workflows/ci-test.yaml
.github/workflows/contracts-test.yaml
clients/js/test/cipher.spec.ts

This PR bumps Node.js to v18.x. Since `nock` used for unit tests of `sapphire-paratime` js client does not support Node.js v18.x yet (https://github.com/nock/nock/issues/2397), the `--no-experimental-fetch` flag is added in the CI tests.

ci: Bump Node.js to v18

---

.github/workflows/ci-test.yaml

This PR removes running onchain-signer for each truffle version combination, because it doesn't rely on truffle.
Followup to https://github.com/oasisprotocol/sapphire-paratime/pull/177.

ci-test: Do not run all truffle combinations for onchain-signer

---

.github/workflows/ci-docs.yaml
.github/workflows/ci-test.yaml
clients/js/README.md
clients/js/package.json
clients/js/tsconfig.json
pnpm-lock.yaml

Generate typedoc for @oasisprotocol/sapphire-paratime package and deploy it to api-reference branch.
Related oasis-sdk isssue https://github.com/oasisprotocol/oasis-sdk/pull/1504.
[Preview](https://api.docs.oasis.io/js/sapphire-paratime/)

clients/js: Add typedoc deployment

---

.github/workflows/ci-docs.yaml
.github/workflows/contracts-test.yaml
contracts/README.md
contracts/foundry.toml

Adds Solidity API reference using `forge doc --build` to generate the markdowns and final HTMLs.
Depends on #186.
[Preview](https://api.docs.oasis.io/sol/sapphire-contracts)

contracts: Add solidity API reference

---

contracts/test/subcall.ts

Latest SDK usage https://github.com/oasisprotocol/sapphire-paratime/pull/192 prevents `0` delegation amount.
https://github.com/oasisprotocol/sapphire-paratime/blob/3a85e42e6c1cc090c28a521cf7df6353aa8a30c8/runtime/src/lib.rs#L196

Skip subcall delegation test

---

.github/workflows/contracts-test.yaml
examples/hardhat/scripts/run-vigil.ts

Improve the robustness of our example script `run-vigil.ts`. Add this workflow to CI.
Supplant #198 due to GitHub weirdness with closing/reopening PR.

Add Hardhat example script `run-vigil.ts` to CI

---

.github/workflows/publish.yaml
CONTRIBUTING.md
README.md

Automatically publish newer versions of different JS packages to NPM if they are not present on the registry already on all pushes to the `main` branch.

Add publish workflow

---

examples/onchain-signer/contracts/Gasless.sol
examples/onchain-signer/hardhat.config.ts
examples/onchain-signer/test/CommentBox.ts

This PR makes examples/onchain-signer tests actually pass on sapphire-testnet.
Merge after #175 since we use the wrapped provider for gasless tx.

examples/onchain-signer/test: Add support for Sapphire Testnet/Mainnet

---

contracts/contracts/Sapphire.sol
contracts/contracts/tests/HashTests.sol
contracts/test/hashes.ts
contracts/test/signing.ts

Have tested this against sapphire-dev from https://github.com/oasisprotocol/oasis-web3-gateway/pull/469

contracts: add SHA384 hash and P-384 curve

---

contracts/contracts/Sapphire.sol
contracts/contracts/tests/Gas.sol
contracts/test/gas.ts

Unfortunately this has different semantics than was initially intended as the initial gas cost for the calldata is added after the transaction is executed.
This means that there will be a 12 gas difference, even after padding, between every NULL and non-NULL byte of the calldata. While this has a very small impact and won't reveal too much sensitive information, it will still reveal *some* information about the encrypted calldata.
A suggested workaround is to add `bytes calldata fuz` argument and filling it with one non-zero byte for every zero byte in the other arguments.

contracts: add gaspad and gasused precompiles

---

.github/workflows/publish.yaml

#203 had a bug where the build step was skipped when publishing.
Specifically, we need to explicitly set `ignore-scripts` to `false` for this [action](https://github.com/JS-DevTools/npm-publish#action-usage). We can see that the only `prepublish` step is to `build`.
https://github.com/oasisprotocol/sapphire-paratime/blob/bcecd07d135adaa85897973087cbe6d380baa07d/clients/js/package.json#L41
I believe that using a separate workflow build step is unnecessary.

Fix missing build on publish

---

.github/workflows/contracts-test.yaml
clients/go/compat.go
clients/js/src/compat.ts
clients/js/src/signed_calls.ts

Relates to #39 
This appears fairly straight forward. I can test with a base Go script against our Vigil [contract](https://github.com/oasisprotocol/sapphire-paratime/blob/4e0434db8677862f9f1ca78735760b283148114e/examples/hardhat/contracts/Vigil.sol).
```Golang
package main
import (
"context"
"crypto/ecdsa"
"fmt"
"log"
"math/big"
"github.com/aefhm/vigil" // or however you do local modules
"github.com/ethereum/go-ethereum/accounts/abi/bind"
"github.com/ethereum/go-ethereum/crypto"
"github.com/ethereum/go-ethereum/ethclient"
sapphire "github.com/oasisprotocol/sapphire-paratime/clients/go"
)
var SapphireChainID = big.NewInt(0x5aff)
func main() {
c, err := ethclient.Dial("https://testnet.sapphire.oasis.dev")
if err != nil {
log.Fatal(err)
}
privateKey, err := crypto.HexToECDSA("")
if err != …
```

Utilize gas estimation in client libraries

---

.github/workflows/contracts-test.yaml
contracts/hardhat.config.ts
examples/hardhat-boilerplate/README.md
examples/hardhat-boilerplate/hardhat.config.js
examples/hardhat/hardhat.config.ts

Make Hardhat network names consistent with the ones that are registered in the [Ethereum chain list](https://github.com/ethereum-lists/chains/tree/master/_data/chains). This is currently:
- sapphire
- sapphire-testnet
- emerald
- emerald-testnet
In the future, we may want to register `sapphire-localnet` and `emerald-localnet` as well, rename the docker image from `sapphire-dev` -> `sapphire-localnet` and update the contracts CI scripts accordingly.

Hardhat: Use sapphire and sapphire-testnet for network names

---

contracts/contracts/Sapphire.sol
contracts/test/hashes.ts

contracts: hashing tests weren't running, which meant sha384 error wasn't caught

---

clients/js/CHANGELOG.md
clients/js/package.json

Draft PR for next client version until #223

Publish JS client 1.2.0

---

.github/workflows/publish.yaml
clients/js/package.json
contracts/test/gas.ts

This requires PNPM to install dependencies first
Bumps clients/js version to v1.2.2
Fixes gas test in contracts (sometimes it's... 1 gas less?)

ci: fix NPM publish + minor contracts tests fix

---

docs/addresses.md

This adds the wROSE wrapper dApp link to the documentation in the standard addresses section.

Update addresses.md with wrose.oasis.io link

---

README.md

[Preview](https://github.com/oasisprotocol/sapphire-paratime/tree/CedarMist/bundlephobia)
This adds:
* Monthly downloads (for NPM packages)
* Bundle size (for JS packages)
* Table instead of list for badges
* Badge for contracts-test CI step
* License icon
Inspiration: 
* https://github.com/privacy-scaling-explorations/zk-kit

docs: updated README.md with extra badges & links

---

contracts/contracts/opl/Enclave.sol
contracts/contracts/opl/Endpoint.sol

The Celer IM message bus doesn't support custom errors in Solidity, this means that any reverts thrown in the critical path from the OPL code when receiving a message will be ignored and replaced with 'reverted silently' by the Message Bus.
- See: https://github.com/celer-network/sgn-v2-contracts/blob/main/contracts/libraries/Utils.sol#L8
This also removes the unused ERC2771Context from the Enclave contract. (Contracts can still suport ERC2771Context, or other meta-tx standard).
I've updated `BaseEndpoint` to use `_msgSender()` from `Context` so inheriting contracts can override it with their meta-tx scheme of choice.

contracts: remove custom reverts and ERC2771Context

---

.github/workflows/contracts-test.yaml
contracts/hardhat.config.ts
docs/guide.mdx
examples/onchain-signer/README.md
examples/onchain-signer/test/CommentBox.ts

This PR renames sapphire-dev to sapphire-localnet in the docs and CI.
Merge after https://github.com/oasisprotocol/oasis-web3-gateway/pull/507.

fix: Rename sapphire-dev to sapphire-localnet

---

docs/security.md

Relates to https://github.com/oasisprotocol/docs/issues/509#issuecomment-1799192990

Add Security documentation to ensure finality

---

clients/js/package.json
clients/js/scripts/proxy.ts
clients/js/src/calldatapublickey.ts
clients/js/src/cipher.ts
clients/js/src/compat.ts
clients/js/src/interfaces.ts
clients/js/test/cipher.spec.ts
clients/js/test/compat.spec.ts
contracts/test/eip155.ts
contracts/test/gas.ts

This should fix several long-standing issues with call encryption.
Previously the `Cipher` object would be created and maintained with the same keys throughout the duration of the session, it also did not support the new `Epoch` flag which specifies which calldata public key was being used to encrypt the request (requiring the server to try several).
This would cause problems, like when you leave a dApp open for a while your transactions would fail with 'tag verification failed'.
This introduces several changes:
* New Cipher instance is used for every request
* calldata public key is cached (5 minutes by default)
* The `epoch` parameter is passed in the encryption envelope
* Debug `scripts/proxy.js` shows epoch status too.
This means that leaving dApps open for prolonged periods of time …

Refactor callDataPublicKey handling

---

examples/ethersv6-ts-esm/src/index.ts

Double check that reversion with error message works with Ethers v6

examples: added require() reversion message check to ethers v6 client

---

contracts/test/signing.ts

Closes #224. The underlying problem was that the random "corrupt" bytes sometimes matched the original message, so verification that should have failed didn't.

contracts: fix flaky signing tests

---

docs/_fetch-cbridge-tokens.py
docs/addresses.md

This includes all of Celer's token addresses which are bridged to/from Oasis Sapphire.

docs: added script to retrieve Celer cBridge token addresses

---

.github/workflows/ci-docs.yaml

We need to `pnpm install` or otherwise install dependencies before generating docs. https://github.com/oasisprotocol/sapphire-paratime/actions/runs/8301914337/job/22724066016

Fix CI dependencies

---

contracts/contracts/opl/Endpoint.sol

Our usage of `Context` is minimal.

Remove OpenZeppelin Context

---

runtime/Makefile
runtime/README.md

This can be used in conjunction with `sapphire-localnet` to run a custom debug build of Sapphire runtime without rebuilding the oasis-web3-gateway image.
Example of bind-mounting sapphire-paratime executable:
SAPPHIRE_DEV_DOCKER=ghcr.io/oasisprotocol/sapphire-localnet:latest
docker run --rm -ti -p8545:8545 -p8546:8546 -v $SOURCE/sapphire-paratime/runtime/target/debug/sapphire-paratime:/runtime.elf $(SAPPHIRE_DEV_DOCKER) -to 'test test test test test test test test test test test junk' -n 4
out of curiosity, here is a Dockerfile that does a full oasis-web3-gateway build with a specific branch: https://gist.github.com/CedarMist/87255bf16f48db3a5b6f7f03d72ccb40 - although it still requires a branch on sapphire-paratime to update Cargo.toml with the correct dependency from oasis-sdk

Added Makefile to `runtime` directory to make debug build for testing

---

runtime/README.md

Followup to #291
@CedarMist Sorry for not being explicit in https://github.com/oasisprotocol/sapphire-paratime/pull/291#discussion_r1540920514, github doesn't like puting ``` in the suggested fix dialog.

runtime: Fix README.md ending ticks

---

contracts/CHANGELOG.md
contracts/package.json

Release patch version of contracts to include dependencies as seen in #180. This PR is blocked by #289.
Let's also get in #290.

contracts: bump to v0.2.8

---

docs/guide.mdx

Adds `-test-mnemonic` description and updates sapphire-localnet specs.

docs: Update docker specs, add -test-mnemonic flag

---

docs/_fetch-cbridge-tokens.py
docs/addresses.md

Add Celer IM message executor.
Add Safe Singleton Factory.

Update documented addresses

---

clients/py/README.md

Add instructions for `web3.py` usage with minimal additional infrastructure.
Devs should select recommended gas strategy as per https://github.com/oasisprotocol/oasis-web3-gateway/issues/501

Update Python client instructions

---

docs/deployment.md

Add technical notes on proxies.
Relates to https://github.com/oasisprotocol/docs/pull/818.

Add deployment pattern recommendations

---

docs/guide.mdx

- describes a way to fund a contract without triggering the receive() or fallback() functions.
- adds proper subsections to the *Ethereum vs Sapphire* differences section
- adds the Instant finality subsection
[PREVIEW](https://deploy-preview-318--oasisprotocol-sapphire-paratime.netlify.app/dapp/sapphire/guide#override-receive-and-fallback-when-funding-the-contract)

docs: Adds section for funding the contract without receive()

---

contracts/contracts/DateTime.sol
contracts/contracts/SiweParser.sol
contracts/contracts/auth/A13e.sol
contracts/contracts/auth/SiweAuth.sol
contracts/contracts/tests/DateTimeTests.sol
contracts/contracts/tests/SiweParserTests.sol
contracts/contracts/tests/auth/SiweAuthTests.sol
contracts/package.json
contracts/test/auth.ts
contracts/test/datetime.ts
contracts/test/gas.ts
contracts/test/siweparser.ts
pnpm-lock.yaml

Fixes #327 
This PR:
- adds `contracts/SiweParser.sol`, an on-chain parser for SIWE messages
- adds `contracts/auth/A13e.sol`, an abstract interface for authenticated queries (an alternative to signed queries which will get deprecated in https://github.com/oasisprotocol/sapphire-paratime/pull/303)
- adds `contracts/auth/SiweAuth.sol`, an on-chain authenticator for SIWE.
- tests, natspec docs + example
TODO:
```solidity
contract MyContract {
address private _owner;
modifier onlyOwner() {
if (msg.sender != _owner) {
revert("not allowed");
}
_;
}
constructor() {
_owner = msg.sender;
}
function getSecretMessage() external view onlyOwner returns (string memory) {
return "Very secret message";
}
}
```
```solidity
import {SiweAuth} from …
```

sapphire-contracts: Add EIP-4361 SIWE parser and base contract

---

contracts/CHANGELOG.md
contracts/contracts/Subcall.sol
contracts/contracts/tests/SubcallTests.sol
contracts/package.json
contracts/test/subcall.ts

contracts: fix CBOR unsigned int decoding in Subcall.sol

---

contracts/contracts/Subcall.sol

We passed in the kind of `UndelegateStart` or 1 when we need `UndelegateDone` or 2.

contracts: Fix subcall undelegation done

---

clients/py/requirements.txt
contracts/contracts/tests/SiweParserTests.sol

* Updates `clients/py` requirements to specify Web3.py v6.x
* Fixes warnings in `contracts/tests/SiweParserTests.sol`

contracts: silence SIWE Solidity tests compile warnings

---

.github/workflows/publish.yaml

fixes: #362
includes: #358
extracts the following tags:
* rc
* next
* alpha
* beta
also enables NPM provenance when publishing
We can change the dist-tag for the `latest` tag: https://stackoverflow.com/questions/67813980/how-to-point-latest-dist-tag-to-a-previous-version-in-npm
```bash
npm dist-tag add <pkg name>@<version> latest
```
And release new versions under the appropriate `alpha` or `beta` tags. Maybe as @matevz recommended we should just use `next` ?

packaging: use PNPM for publishing, with correct tags

---

clients/js/CHANGELOG.md
clients/js/package.json
integrations/ethers-v6/CHANGELOG.md
integrations/ethers-v6/package.json
integrations/hardhat/CHANGELOG.md
integrations/hardhat/package.json
integrations/viem-v2/CHANGELOG.md
integrations/viem-v2/package.json
integrations/wagmi-v2/CHANGELOG.md
integrations/wagmi-v2/package.json

re: #362
re: #363
for the following packages:
* oasisprotocol/sapphire-paratime
* oasisprotocol/sapphire-ethers-v6
* oasisprotocol/sapphire-hardhat
* oasisprotocol/sapphire-viem-v2
* oasisprotocol/sapphire-wagmi-v2
They will be released under the `next` tag, to test updated publish.yaml workflow
after publishing the bundlephobia links in the main README.md should work
It should also be possible to install the packages & resolve their dependencies.

packaging: bump versions + add CHANGELOG entries

---

.github/workflows/publish.yaml
clients/js/package.json

Publishing with pnpm failed as we're trying to publish with provenance, but it doesn't have the necessary permissions in the workflow.
This error message was in logs:
```
npm notice Publishing to https://registry.npmjs.org/ with tag next and public access
npm error code EUSAGE
npm error Provenance generation in GitHub Actions requires "write" access to the "id-token" permission
```
See:
* https://github.blog/news-insights/product-news/introducing-artifact-attestations-now-in-public-beta/
* https://docs.github.com/en/actions/writing-workflows/workflow-syntax-for-github-actions#permissions
* https://docs.github.com/en/actions/security-for-github-actions/using-artifact-attestations/using-artifact-attestations-to-establish-provenance-for-builds
* …

packaging: permissions necessary for provenance pubishing

---

contracts/CHANGELOG.md
contracts/contracts/Subcall.sol
contracts/contracts/tests/SubcallTests.sol
contracts/package.json
contracts/test/subcall.ts

Adds two methods to `Subcall.sol`
* `coreCallDataPublicKey`
* `coreCurrentEpoch`

contracts: add support for core.CallDataPublicKey and core.CurrentEpoch

---

docs/browser.md
docs/quickstart.mdx

Fixes broken links introduced in https://github.com/oasisprotocol/sapphire-paratime/pull/303
Now points to the stable/clients/js/1.x branch.

docs: Fix broken links to Vigil.sol contract

---

docs/browser.md
docs/gasless.md
docs/quickstart.mdx

Fixes https://github.com/oasisprotocol/demo-starter-go/issues/2.
This PR:
- adds demo-starter-go and demo-starter-py references
- makes usage of  `:::info Example:` consistent
Merge after https://github.com/oasisprotocol/demo-starter-py/pull/1.

docs: Mention demo-starter-go and demo-starter-py

---

integrations/viem-v2/package.json
integrations/viem-v2/scripts/test.js
integrations/viem-v2/src/index.ts

clients/viem: use interval for routine fetching, unref intervalId

---

clients/js/package.json
integrations/ethers-v6/package.json
integrations/hardhat/package.json
integrations/viem-v2/CHANGELOG.md
integrations/viem-v2/package.json
integrations/wagmi-v2/package.json

So, need to re-release packages to get versioning working correctly.
So, we're going to archive:
* `@oasisprotocol/sapphire-paratime` v2.0.0-alpha.0 on the `latest` tag
* `@oasisprotocol/sapphire-paratime` v2.0.0-next.3 on the `next` tag
Then release `@oasisprotocol/sapphire-paratime` v2.0.0 on the `next` tag
The `sapphire-viem-v2`, `sapphire-ethers-v6`, `sapphire-hardhat` and `sapphire-wagmi-v2` packages will be published on their own `latest` tags.
Meaning people who `npm install @oasisprotocol/sapphire-paratime` will get v1.x by default, but if you install `@oasisprotocol/sapphire-ethers-v6` you'll get `@oasisprotocol/sapphire-paratime` v2 as a dependency.
This means we'll be tagging `clients/js/v2.0.0-next` (to publish to the `next` dist-tag on NPMJS), but …

packaging: remove semver tags from package versions

---

integrations/ethers-v6/package.json

integrations/ethers-v6: make sapphire-paratime a non-optional dependency

---

clients/js/test/utils.ts

Other PRs are showing minor warnings.
This hides the warnings by removing the unused vars.

clients/js: fix lint warnings in tests

---

clients/js/CHANGELOG.md
clients/js/package.json

Ready to release `@oasisprotocol/sapphire-paratime` package on npmjs
Need to tag `clients/js/v2.0.1-next`

packaging: bump clients/js to 2.0.1 and update CHANGELOG

---

docs/README.mdx
docs/browser.md
docs/guide.mdx

Use new Sapphire page content and update anchors to reference Network page.
Fix links introduced in #402.
```sh
Exhaustive list of all broken anchors found:
- Broken anchor on source page path = /dapp/sapphire/browser:
-> linking to /dapp/sapphire/#testnet
- Broken anchor on source page path = /dapp/sapphire/guide:
-> linking to /dapp/sapphire/#rpc-endpoints
```
https://github.com/oasisprotocol/docs/actions/runs/10951224600/job/30407909516?pr=940

docs: Update main Sapphire page content

---

docs/deployment.md

Close https://github.com/oasisprotocol/sapphire-paratime/issues/350 by noting full support.

docs: Add EIP-1167 minimal proxy section

---

examples/wagmi-v2/README.md
integrations/viem-v2/README.md
integrations/viem-v2/src/index.ts
integrations/wagmi-v2/README.md

`sapphireTransport` was renamed in 67616921797dca03557c6bc6d911a5ec883cc179

Fix references to sapphireHttpTransport

---

docs/_fetch-cbridge-tokens.py
docs/addresses.md

Update fetch script to ignore Goerli and Mumbai. Close https://github.com/oasisprotocol/docs/issues/962

docs: Remove cbridge listings for deprecated networks Goerli and Mumbai

---

.github/workflows/ci-test-go.yaml
.github/workflows/ci-test.yaml
clients/go/cipher.go
clients/go/compat.go
clients/go/compat_test.go

fixes: #421
adds tests for performing a value transfer (doesn't check if encryption works)

clients/go: use existing RPC connection to retrieve calldata public key

---

contracts/contracts/tests/auth/SiweAuthTests.sol
contracts/test/auth.ts

fixes: #361
Also fixes typescript warnings in auth.ts

contracts: fix intermittent failures in auth.ts tests

---

integrations/viem-v2/README.md
integrations/viem-v2/hardhat.config.cjs
integrations/viem-v2/package.json
integrations/viem-v2/test/docs.test.ts
pnpm-lock.yaml

Adds tests to ensure the README.md examples from integrations/viem-v2 can be imported.
This will catch any glaring errors. I think we should extend this to all of the packages in this repo.

integrations/viem: doctests

---

contracts/contracts/Sapphire.sol

Fixes https://github.com/oasisprotocol/sapphire-paratime/issues/430

contracts/generateSigningKeypair: Doc explicit sk size

---

contracts/test/auth.ts
contracts/test/gas.ts

Fixes #443 by waiting for the block with sufficiently new timestamp instead of fixed time.
Another workaround for #337.

contracts/tests: Fix flaky SIWE and gas cost

---

contracts/test/gas.ts

Another followup to https://github.com/oasisprotocol/sapphire-paratime/pull/444
Noticed the gas error right after:
https://github.com/oasisprotocol/sapphire-paratime/actions/runs/11499202245/job/32006650394?pr=445
I hope this is the final fix for the intermittent gas errors now.

contracts/test: Fix intermittent initial gas error

---

contracts/contracts/CBOR.sol
contracts/contracts/Subcall.sol
contracts/contracts/tests/SubcallTests.sol
contracts/contracts/tests/TestCBOR.sol
contracts/package.json
contracts/test/cbor.spec.ts
contracts/test/subcall.ts
contracts/tsconfig.json

as per @matevz 's request, I am splitting https://github.com/oasisprotocol/sapphire-paratime/pull/436 into several smaller ones for clarity.

contracts: move CBOR related encoding & decoding into separate module

---

clients/js/src/provider.ts

Close #385 maybe.
Wagmi is concerned with bad implementations of `EIP-1193` and wants to check that the `removeListener` function [exists](https://github.com/wevm/wagmi/blob/86c42248c2f34260a52ee85183c607315ae63ce8/packages/core/src/connectors/injected.ts#L327-L335). However, the Brave wallet overrides `ethereum` [properties](https://github.com/brave/brave-core/blob/74bf470a0291ea3719f1a75af066ee10b7057dbd/components/brave_wallet/resources/ethereum_provider.js#L13-L27) and does not like the way we currently use `Proxy` objects, giving a typeerror upon a `get` call.
Our current implementation is a classic Proxy [pattern](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Proxy#no_private_property_forwarding) in order to preserve `this`.
```JavaScript
const …
```

clients: Support Brave wallet default

---

clients/js/src/cipher.ts
clients/js/test/cipher.spec.ts
contracts/contracts/CalldataEncryption.sol
contracts/contracts/tests/TestCalldataEncryption.sol
contracts/test/calldata.spec.ts

Closes: #436
Implements calldata encryption to create encrypted transactions from contracts on Sapphire.
This also updates Cipher TS to accept an optional `nonce` parameter, this means we can do easier deterministic tests to verify the Solidity implementation matches the Typescript implementation.

contracts: calldata encryption function (Solidity)

---

.github/workflows/ci-playwright.yaml
README.md
examples/wagmi-v2/.gitignore
examples/wagmi-v2/package.json
examples/wagmi-v2/playwright.config.ts
examples/wagmi-v2/src/App.tsx
examples/wagmi-v2/test/e2e.spec.ts
pnpm-lock.yaml

Actually close #417 this time.

examples: Add e2e testing with dAppwright

---

contracts/contracts/EIP1559Signer.sol
contracts/contracts/EIP2930Signer.sol
contracts/contracts/EIPTypes.sol
contracts/contracts/tests/EIPTests.sol
contracts/test/eip1559_2930.ts

This PR adds libraries for signing Type1 (EIP-2930) and Type2 (EIP-1559) transactions as described in #321 
TODO:

Add EIP1559 and EIP2930 signer libraries.

---

.github/workflows/ci-playwright.yaml
.github/workflows/ci-test-go.yaml
.github/workflows/contracts-test.yaml

Note that I haven't found a way to pass the script arguments to the end of the Docker run command from GitHub Actions, but the nice part is that they don't really matter, since the test mnemonic and 5 accounts is already the default :man_shrugging:
Closes #465.

ci: Fix Docker options after removing oasis-deposit

---

docs/network.mdx

Docs are referring to deprecated API that will be removed soon. PR updates Oasis Scan links to v2 which is currently used by BitCat.
Part of https://github.com/oasisprotocol/wallet/issues/2086

Update Oasis Scan API urls

---

docs/quickstart.mdx

Use the nocookie version of the YouTube embedding for the Sapphire's video tutorial by @CedarMist . Inspired by https://github.com/oasisprotocol/docs/pull/1035.
Also fixes YT integration for Firefox (no fullscreen previously).

docs/sapphire/quickstart: Use youtube-nocookie

---

docs/README.mdx
docs/guide.mdx

fixes the links which get broken through [1041](https://github.com/oasisprotocol/docs/pull/1041)
Merge after https://github.com/oasisprotocol/sapphire-paratime/pull/466

fix: links to emerald and cipher

---

docs/gasless.md
examples/onchain-signer/contracts/Gasless.sol
examples/onchain-signer/hardhat.config.ts
examples/onchain-signer/package.json
examples/onchain-signer/test/CommentBox.ts

This PR:
- documents `encryptCallData()` in `gasless.md` to generate encrypted gasless transaction
- adds `encryptCallData()` to `examples/onchain-signer` and tests it in combination with the wrapped/unwrapped provider and encrypted/plain gasless tx.
- removes some unneeded sleeps from the onchain-signer tests since the recent sapphire-localnet healthcheck correctly waits that the EVM is spun up before running them
[PREVIEW](https://deploy-preview-477--oasisprotocol-sapphire-paratime.netlify.app/dapp/sapphire/gasless)
Fixes #463.

Add encryptCallData() to gasless chapter and example

---

.github/workflows/ci-docs.yaml
clients/py/.gitignore
clients/py/Makefile

This PR adds python client [documentation ](https://www.sphinx-doc.org/en/master/) to https://api.docs.oasis.io/

Docs: Add python client

---

contracts/contracts/opl/Endpoint.sol

Update library to remove the no longer maintained testnets.

contracts: Remove deprecated Celer testnets in OPL library

---

contracts/contracts/Sapphire.sol

This should have been removed a year ago actually when Sapphire 0.6.x branch wasn't running on Mainnet anymore.

contracts: Remove Sapphire.randomBytes() obsolete warning

---

docs/develop/concept.mdx

A small fix for linking the `sapphire-paratime` npm package properly.

docs/develop: Fix npm package link for sapphire-paratime in concept.mdx

---

clients/js/src/cipher.ts
clients/js/src/provider.ts
clients/js/test/cipher.spec.ts
integrations/ethers-v6/src/index.ts

fixes #389
This provides the decryption keys to snap.
> [!WARNING]
> If an RPC server pretends to implement the MetaMask snap protocol it could trick users into revealing the transaction encryption key. 
>
> For this reason, we have to explicitly enable Snap support in the dApp, by passing the `enableSapphireSnap` option.
Usage:
```typescript
wrapEthereumProvider(window.ethereum, {enableSapphireSnap:true})
```
```typescript
wrapEthersProvider(ethProvider, { enableSapphireSnap: true })
```
This must only be done if the dApp is sure that the provider it's connecting to is MetaMask.
Next PRs handled by Sapphire team: 
* Automated tests for `wallet_invokeSnap`
* Use flask for testing https://docs.metamask.io/snaps/get-started/install-flask/

Initial work to implement Sapphire snap connection

---

.github/workflows/ci-test-demos.yaml
.github/workflows/ci-test-go.yaml

Close #328 by using https://github.com/oasisprotocol/demo-starter-go as a submodule for end-to-end testing. The drawback is that approach is less consistent with current behavior inside [`examples/`](https://github.com/oasisprotocol/sapphire-paratime/tree/main/examples) but introduces less code.

clients/go: Add e2e Go client test

---

clients/js/src/provider.ts
integrations/viem-v2/src/index.ts
integrations/wagmi-v2/src/index.ts

`wrapEthereumProvider` has params which are not accessible for Wagmi and Viem integrations. To allow Snap connections we need to pass wrap config.

Enable Snap connections for Wagmi and Viem integrations

---

integrations/hardhat/CHANGELOG.md
integrations/hardhat/package.json

Close #505.
Note. We are including this set of changes: https://github.com/oasisprotocol/sapphire-paratime/pull/449, https://github.com/oasisprotocol/sapphire-paratime/pull/411, https://github.com/oasisprotocol/sapphire-paratime/pull/431 due to the non-branching publish process. Alternatively, we would cut at this [point](https://github.com/oasisprotocol/sapphire-paratime/releases/tag/integrations%2Fhardhat%2Fv2.22.2-next), and separately but also slightly more confusingly bump `package.json` that way.

integrations: Publish `sapphire-hardhat` 2.22.2

---

clients/js/CHANGELOG.md
clients/js/package.json

clients/js: Bump JS client to 2.1.0

---

.github/workflows/ci-test.yaml

Setuptools was updated in actions/setup-python@v5, which means dot (.) and dash (-) symbols in lib name are automatically changed to underscore ( _ ). This PR fixes it in the ci-test py workflow.

Fix sapphire_py whl file naming

---

.github/workflows/publish.yaml
contracts/contracts/.soldeerignore

This PR adds ([issue](https://github.com/oasisprotocol/sapphire-paratime/issues/496)):
- contracts/contracts folder to SolDeer repository through publish.yaml workflow
- .soldeerignore file for .npmignore
TODO: We have to add the SOLDEER_ACCESS_TOKEN to github secrets.

Add SolDeer contracts upload to publish.yaml workflow

---

contracts/contracts/auth/SiweAuth.sol
contracts/contracts/tests/auth/SiweAuthTests.sol
contracts/test/auth.ts
docs/develop/authentication.md

I stumbled on this when deploying demo-rofl-chatbot contract on Testnet and as a test I set the initial domain to `localhost`. When I wanted to simply change it to `playground.oasis.io`, I realized it can't be done, because `_domain` is `private` in the super contract.
[Preview](https://deploy-preview-529--oasisprotocol-sapphire-paratime.netlify.app/build/sapphire/develop/authentication#siwe-domain)

contracts/auth/SiweAuth: Change _domain visibility to internal

---

.github/workflows/ci-docs.yaml
.github/workflows/ci-test.yaml
examples/Makefile
examples/foundry/Makefile
examples/foundry/README.md
examples/foundry/foundry.toml
examples/foundry/lib/oasisprotocol-sapphire-contracts
examples/foundry/lib/oasisprotocol-sapphire-foundry
examples/foundry/src/CommentBox.sol
examples/foundry/src/Counter.sol
examples/foundry/src/Gasless.sol
examples/foundry/test/TestCommentBox.t.sol
examples/foundry/test/TestCounter.t.sol
integrations/Makefile
integrations/foundry/Makefile
integrations/foundry/README.md
integrations/foundry/foundry.toml
integrations/foundry/lib/oasisprotocol-sapphire-contracts
integrations/foundry/lib/oasisprotocol-sapphire-foundry/BaseSapphireTest.sol
integrations/foundry/lib/oasisprotocol-sapphire-foundry/BinaryContracts.sol
integrations/foundry/lib/oasisprotocol-sapphire-foundry/BinaryHandler.sol
integrations/foundry/lib/oasisprotocol-sapphire-foundry/Precompiles.sol
integrations/foundry/lib/oasisprotocol-sapphire-foundry/precompiles/.cargo/config.toml
integrations/foundry/lib/oasisprotocol-sapphire-foundry/precompiles/Cargo.toml
integrations/foundry/lib/oasisprotocol-sapphire-foundry/precompiles/src/main.rs
integrations/foundry/test/TestPrecompiles.t.sol
integrations/foundry/test/TestSapphireContracts.t.sol

This PR:
- Adds boilerplate Foundry contracts that simulate Sapphire precompiles and decryption
- Implements Foundry tests
- Contains Rust FFI bindings
- Added Makefile with build, test, clean options
- Readme with instructions
Enables local testing of Sapphire-compatible contracts without using forks.

feat: Add Foundry toolkit that enables Sapphire precompile and decryption

---

.github/workflows/ci-docs.yaml
.github/workflows/publish.yaml

This PR:
- Adds soldeer token folder in publish.yaml
- Removes integrations/Foundry folder from js-docs loop.

Ignore integrations Foundry docs and add soldeer token folder

---

examples/hardhat/hardhat.config.ts
examples/hardhat/tasks/index.ts

Fix older style comment `sapphire-dev` to `sapphire-localnet`. Fix spelling.

examples: Fix spelling and Hardhat private key reference

---

contracts/contracts/auth/SiweAuth.sol
contracts/contracts/tests/auth/SiweAuthTests.sol
contracts/test/auth.ts

* Added `statement` and `resources` fields to the `AuthToken` structure 
* Implemented functions to retrieve the statement and resources from an authentication token, and a helper function to decode and validate tokens 
* Added test functions to `SiweAuthTests` for retrieving statements and resources
* Updated test cases to verify the new functionality, including tests for statement verification, resource access

feat: Add statement and resources for SIWE authentication

---

.github/workflows/ci-lint.yaml
.github/workflows/ci-test.yaml
integrations/foundry/lib/oasisprotocol-sapphire-foundry/precompiles/Cargo.toml

This PR addresses build failures caused by recent updates to the time crate (v0.3.41) and its dependency deranged (v0.4.1).
- Recent releases of the time crate (after v0.3.36) pull in deranged v0.4.1
- This newer version of deranged introduces changes to trait implementations that cause type inference errors
- The specific error occurs in runtime/src/common/sgx/ias.rs with ambiguous trait implementations
Fix:
- Patched the time crate to use v0.3.36 from GitHub (released April 11, 2024)
- Update Foundry cmake version in ci-test.yaml

Fix: Pin time crate to v0.3.36 to resolve type inference regressions

---

docs/addresses.md

This pull request includes changes to the `docs/addresses.md` file to update the list of standard contract addresses. The changes primarily focus on improving the readability and consistency of the documentation.
Documentation updates:
* Reformatted the table to include links to both mainnet and testnet addresses for each contract.
* Removed the "Verify" column from the table and replaced it with direct links to the contract addresses on the Oasis explorer.
* Updated the references to the contract addresses to use new link labels for better clarity.
* Adds Router Nitro tokens #549 
[PREVIEW](https://deploy-preview-553--oasisprotocol-sapphire-paratime.netlify.app/build/sapphire/addresses)

docs: add multicall v3 testnet

---

docs/addresses.md

This pull request includes updates to the `docs/addresses.md` file, specifically in the list of standard contract addresses. The main changes involve correcting the links for the Router Asset Forwarder and Router Asset Bridge contracts.
Corrections to contract addresses:
* [`docs/addresses.md`](diffhunk://#diff-509064a9a3703646abc17e5e499d116452b17843787f44d078111104eeb802afL76-R77): Corrected the links for the Router Asset Forwarder and Router Asset Bridge contracts in the list of standard contract addresses.

docs: fix links in addresses.md

---

.github/workflows/ci-test.yaml
.github/workflows/publish.yaml
clients/py/README.md
clients/py/requirements.txt
clients/py/sapphirepy/sapphire.py
clients/py/sapphirepy/tests/test_async_e2e.py
clients/py/sapphirepy/tests/test_e2e.py

This PR updates web3.py version in sapphirepy from 6.x to 7.x.
Changes:
- sapphire.py Now uses 7.x class based middleware with changes to block_hash parsing (new hexbytes version).
- test_e2e.py updated
TODO:
In addition, this PR also updates the publish.yaml workflow with PyPI tag release.

Bump web3py to 7.x

---

clients/py/CHANGELOG.md
clients/py/setup.py

This PR:
- adds CHANGELOG.md to clients/py wrapper library
- updates version from 0.3.0 to 0.4.0 in clients/py/setup.py

clients/py: Prepare 0.4.0 release

---

clients/py/setup.py

Change package name (sapphire.py -> oasis-sapphire-py) to allow upload to [PyPI](https://pypi.org/project/oasis-sapphire-py/#description).
Issue: https://github.com/oasisprotocol/sapphire-paratime/issues/561
The import still works the same `import sapphirepy`.

Change package name to oasis-sapphire-py

---

examples/wagmi-v2/package.json
examples/wagmi-v2/test/e2e.spec.ts

This pull request includes updates to the `examples/wagmi-v2` project to improve the test suite and update dependencies. The most important changes include updating the `@tenkeylabs/dappwright` dependency and enhancing the end-to-end test script to handle page navigation and account switching more robustly.
Dependency updates:
* [`examples/wagmi-v2/package.json`](diffhunk://#diff-f7d8de0ffe97f6e81f56d48f2a99b5cc11f198833d91ec1eab9b98f75ec0a3b9L22-R22): Updated `@tenkeylabs/dappwright` dependency from version `^2.8.6` to `^2.10.0` which includes the fix for account selection by name
* Fixed MetaMask version to 12.10.4 to address issues with enabling testing networks during CI setup. See [TenKeyLabs/dappwright#426](https://github.com/TenKeyLabs/dappwright/issues/426) for details. …

Update dappwright dependency and enhance e2e tests for wallet account switching

---

.github/workflows/publish.yaml

This PR fixes: 
- `publish-contracts-soldeer` job error in publish.yaml. 
- Token expiration issue
Missing `actions/checkout@v4` resulted in combined working directory paths (/home/runner/work/**sapphire-paratime/sapphire-paratime**/contracts/contracts)
Soldeer API token expires after 1 month which makes it unsuitable as a github secret. The soldeer CI/CD has been updated to use email/password combination.
Fix: Added `actions/checkout@v4` to `publish-contracts-soldeer`.
Fixes https://github.com/oasisprotocol/sapphire-paratime/issues/561

Add checkout action to soldeer CI

---

.github/workflows/ci-docs.yaml
.github/workflows/ci-lint.yaml
.github/workflows/ci-playwright.yaml
.github/workflows/ci-test.yaml
.github/workflows/contracts-test.yaml
.github/workflows/publish.yaml
examples/wagmi-v2/package.json
integrations/viem-v2/package.json
package.json
pnpm-lock.yaml
pnpm-workspace.yaml

This pull request streamlines the GitHub Actions workflows, updates dependencies, and introduces a new `package.json` file for the project. The most notable changes include simplifying the setup of `pnpm` and caching, updating the `viem` dependency to a more flexible version range, and adding a `package.json` file with project metadata and configuration.
* all workflows use now `pnpm install --frozen-lockfile`
* all workflows use now the package manger from root `package.json` via `pnpm/action-setup@v4`
* Replaced the manual setup of `pnpm` and caching in all workflows (`ci-docs`, `ci-lint`, `ci-playwright`, `ci-test`, `contracts-test`, `publish`) with the `cache: 'pnpm'` option in `actions/setup-node@v4` for improved maintainability. Also removed redundant steps like `pnpm store path` …

fix: update CI workflows to use corepack and install dependencies with frozen lockfile

---

contracts/contracts/Sapphire.sol

Enhance the documentation for the `sign()` and `verify()` functions in Sapphire.sol to clarify how the `contextOrHash` parameter should be used with different signing algorithms:
- Correct the expected hash size for Secp384r1PrehashedSha384 from 32 bytes to 48 bytes
- Add detailed explanations of parameter behavior for each algorithm type
- Explicitly document that Sr25519 signatures MUST use "substrate" as the context for compatibility with Substrate off-chain signing using { withType: true }
- Add clear code examples showing proper usage for different algorithms
- Maintain consistent documentation between sign() and verify() functions

docs: improve contextOrHash parameter documentation

---

integrations/wagmi-v2/src/index.ts

Alternative of https://github.com/oasisprotocol/sapphire-paratime/pull/565, by patching `window.dispatchEvent` instead of `addEventListener`.

sapphire-wagmi-v2: Patch dispatchEvent instead of addEventListener

---

examples/foundry/Makefile
integrations/foundry/Makefile

This PR fixes following issue:
- `--no-commit` flag was updated to `--commit` in new foundry version, so we can remove it from the CI

Remove --no-commit flag

---

integrations/wagmi-v2/CHANGELOG.md
integrations/wagmi-v2/package.json

Fixes #563 
Merge after https://github.com/oasisprotocol/internal/issues/64 is fixed.
May also wait for https://github.com/oasisprotocol/sapphire-paratime/pull/565 or make a 2.1.1 bugfix release afterwards.

integrations/wagmi-v2: Prepare 2.1.0 release

---

clients/js/src/calldatapublickey.ts
clients/js/src/provider.ts

Fixes https://github.com/oasisprotocol/sapphire-paratime/issues/583

clients/js: Don't throw on eth_chainId request on non-sapphire chain

---

examples/wagmi-v2/test/e2e.spec.ts

Metamask seems to name the accounts weird in the setup (maybe different every version?)
"jvh" corresponds to address 0x70997970C51812dc3A010C7d01b50e0d17dc79C8

fix: account switching an dappwright

---

contracts/contracts/Subcall.sol
contracts/contracts/tests/SubcallTests.sol
contracts/test/subcall.ts

Fixes https://github.com/oasisprotocol/sapphire-paratime/issues/600
I tested this using Sapphire Localnet and https://github.com/oasisprotocol/oasis-sdk/tree/4fd04825de470b0b0eda25ed388c4efc93ea9283/examples/runtime-sdk/rofl-oracle-sgx with a modified contract to initiate a call.

contracts: Add getRoflAppId helper for rofl.OriginApp subcall

---

docs/develop/deployment.md
docs/ethereum.mdx

Merge once Sapphire with https://github.com/oasisprotocol/oasis-sdk/pull/2215 is live.

Update eth_getStorageAt docs with whitelisted storage slots

---

integrations/wagmi-v2/src/index.ts

- looks like export const due to generic type didn't work
Built upon https://github.com/oasisprotocol/sapphire-paratime/pull/607

wagmi-v2: Fix TypeDoc issue

---

contracts/CHANGELOG.md
contracts/package.json

The new `getRoflAppId()` helper was merged [a while ago](https://github.com/oasisprotocol/sapphire-paratime/pull/606), but it took a while to test it in production.

contracts: Prepare 0.2.15 release
