oasisprotocol/sapphire-paratime

Cargo.lock, runtime/Cargo.toml
// TODO(me): make a CI script for this that automatically creates tags when the cargo ver is bumped...
=> runtime: bump Cargo.toml version

.github/workflows/release.yaml
resolves follow up comments of #29
=> ci: twiddle debug ORC

clients/js/package.json, clients/js/pnpm-lock.yaml, clients/js/src/compat.ts, clients/js/test/compat.spec.ts
This PR works around #39 and #41 .
=> clients/js: use DEFAULT_GAS in more places

clients/js/package.json, clients/js/pnpm-lock.yaml
Fixes https://github.com/oasisprotocol/sapphire-paratime/issues/48
=> Fix type errors in exported type declaration

.github/workflows/ci-lint.yaml, clients/js/README.md, clients/js/package.json, clients/js/src/compat.ts, clients/js/type-only-test/index.ts, clients/js/type-only-test/package.json, clients/js/type-only-test/pnpm-lock.yaml, clients/js/type-only-test/tsconfig.json
Still reproduces type errors, even with https://github.com/oasisprotocol/sapphire-paratime/pull/49 and https://github.com/oasisprotocol/sapphire-paratime/pull/46 merged in
=> Test and fix types with truffle and other examples from README

clients/go/go.mod
Thanks @lukaw3d for spotting it
=> clients/go: fix module name

clients/js/README.md, clients/js/package.json, clients/js/pnpm-lock.yaml
=> clients/js: add troubleshooting section to README

clients/js/src/cipher.ts, clients/js/tsconfig.json
This setup works ok and closes #56
=> Enable building for CRA@4

clients/js/src/compat.ts
As long as a provider has the 'send' field, we should opportunistically try that to fetch publickey. The network provider of the hardhat environment is neither a provider nor a signer but it has the available 'send' function.
=> we should try 'send' in provider to fetch publickey more

contracts/hardhat.config.ts, contracts/package.json, examples/hardhat/package.json, pnpm-lock.yaml
resolves the following warning
```
You have both ethereum-waffle and @nomicfoundation/hardhat-chai-matchers installed. They don't work correctly together, so please make sure you only use one.
We recommend you migrate to @nomicfoundation/hardhat-chai-matchers. Learn how to do it here: https://hardhat.org/migrate-from-waffle
```
=> contracts: migrate from waffle

contracts/hardhat.config.ts
These are useful for getting the GSN relayer working.
=> contracts: add wrose utility tasks

contracts/contracts/opl/Endpoint.sol
=> Return fee used by postMessage

.github/workflows/ci-test.yaml, clients/js/src/compat.ts
=> Try to appease new & old truffle, as well as ethers v5

examples/hardhat/package.json, integrations/hardhat/package.json, integrations/hardhat/src/index.ts, pnpm-lock.yaml
bump the oasislabs/hardhat version so it should be compatible with hardhat 2.16.1
=> bump oasislabs/hardhat to 2.16.1

.github/ISSUE_TEMPLATE/bug_report.md, .github/ISSUE_TEMPLATE/feature_request.md, CONTRIBUTING.md, README.md
Add base repository README. See reference [repo](https://github.com/oasisprotocol/nexus).
=> Add base repository README

README.md
Includes links to the API documentation in the README
=> README: added api-docs links

examples/hardhat/scripts/run-vigil.ts
I introduced a redundant line earlier.
=> Remove redundant code in example script

clients/go/README.md
Clean up `Go` package instructions.
=> Fix up Go package instructions

.github/wait-until-ready.sh, .github/workflows/contracts-test.yaml
Wait until container with Oasis Gateway is actually ready.
=> Add wait for CI until Oasis Gateway is ready

LICENSE-docs, README.md
See https://github.com/oasisprotocol/docs/pull/440
=> docs: License the documentation under CC BY 4.0

contracts/package.json, pnpm-lock.yaml
Fix #180 and declare Sapphire contracts' dependency explicitly.
~~- [ ] Optionally bump patch version of NPM package~~
=> Fix contracts dependencies

docs/guide.mdx
Merge after https://github.com/oasisprotocol/docs/pull/777
=> docs: Fix deposit ROSE link

clients/go/compat.go
Closes #335.
I've tested `demo-starter-go` with these changes and the following in `go.mod`:
```
replace github.com/oasisprotocol/sapphire-paratime/clients/go => ../sapphire-paratime/clients/go
```
and everything worked -- also the `demo-starter-go` code is nicer now, since it loses one cast and can use the wrapped backend in all go-ethereum calls :)
=> clients/go: Make WrappedBackend also implement DeployBackend

.github/workflows/publish.yaml
Use environment variable to prevent injection [attack](https://docs.github.com/en/actions/security-for-github-actions/security-guides/security-hardening-for-github-actions#using-an-intermediate-environment-variable).
=> workflow: Harden GitHub workflow against injection

.github/workflows/publish.yaml, clients/js/package.json
See: https://github.com/pnpm/pnpm/issues/3141
Workaround is to use `pnpm config set`
=> packaging: fix for PNPM publish auth token

docs/addresses.md
Close #345 via adding necessary deployment information. Blocks https://github.com/oasisprotocol/docs/pull/907.
=> docs: Add Band oracle addresses

CONTRIBUTING.md
Technically, we maintain a list of team members as mandatory reviewers.
=> readme: Update contributions

integrations/ethers-v6/CHANGELOG.md, integrations/ethers-v6/package.json
Need to tag `integrations/ethers-v6/v6.0.1`
=> packaging: integrations/ethers-v6 v6.0.1

integrations/viem-v2/README.md
=> viem2 integration: update readme

docs/README.mdx
Attempt to resolve need to symlink new files introduced in `external/sapphire-paratime` for documentation publish in https://github.com/oasisprotocol/docs/ repository.
=> docs: Add remaining README.mdx file from docs repository

README.md
=> docs: Update instructions for new doc pages

docs/addresses.md
=> docs: createx addresses

docs/addresses.md
[Preview](https://deploy-preview-434--oasisprotocol-sapphire-paratime.netlify.app/dapp/sapphire/addresses#deployments)
=> docs: add router gateway addresses

docs/guide.mdx, docs/network.mdx
Necessary for https://github.com/oasisprotocol/docs/issues/959. Blocked by https://github.com/oasisprotocol/docs/pull/977, and https://github.com/oasisprotocol/cli/pull/310.
=> docs: Sapphire localnet references consolidated page under tools

contracts/contracts/opl/Endpoint.sol
Fix incorrect chain [ID](https://docs.avax.network/dapps/chain-settings).
=> Fix Avalanche fuji chain ID reference

contracts/CHANGELOG.md, contracts/README.md, contracts/package.json
Merge after https://github.com/oasisprotocol/sapphire-paratime/pull/489
=> contracts: Prepare 0.2.12 release

docs/develop/authentication.md
Followup to https://github.com/oasisprotocol/sapphire-paratime/pull/459
This PR:
- Fixes demo-starter link to the master branch now that SIWE support was merged
- Updates the solidity code so that it actually works ;)
- Adds API reference link for SiweAuth contract
- Adds API reference link for the python's `wrap` function
[PREVIEW](https://deploy-preview-491--oasisprotocol-sapphire-paratime.netlify.app/build/sapphire/develop/authentication)
=> docs: Update API reference links and SiweAuth contracts

docs/README.mdx
Fixes broken link in Sapphire README to Develop on Sapphire README
=> fix: link in Sapphire README

docs/develop/authentication.md, docs/examples.mdx
=> docs: Fix wording and link

README.md
Close #242 by documenting crux of release process.
=> docs: Summarize current NPM package release process

examples/hardhat/.gitignore, examples/hardhat/Makefile, examples/hardhat/README.md, examples/hardhat/contracts/Vigil.sol, examples/hardhat/hardhat.config.ts, examples/hardhat/package.json, examples/hardhat/tsconfig.json, pnpm-lock.yaml, pnpm-workspace.yaml
Relates to https://github.com/oasisprotocol/sapphire-paratime/pull/524 but only adds the `examples/hardhat`.
=> examples: Add Sapphire Hardhat example

examples/hardhat/contracts/Vigil.sol, examples/hardhat/hardhat.config.ts, examples/hardhat/tasks/index.ts
https://github.com/oasisprotocol/sapphire-paratime/pull/524 needs a separate bump in `examples/` because Netlify doesn't include new changes.
=> examples: Update Hardhat

docs/develop/dappwright.md
Close #501. See related https://github.com/oasisprotocol/docs/pull/1170 and [preview](https://deploy-preview-1170--oasisprotocol-docs.netlify.app/).
=> docs: Add e2e testing with dappwright

docs/quickstart.mdx
=> docs: Update Quickstart to Use V2 Hardhat Example

docs/quickstart.mdx
All the rebasing in https://github.com/oasisprotocol/sapphire-paratime/pull/524 lost a change.
=> docs: Fix typo

docs/network.mdx
Fixes https://github.com/oasisprotocol/docs/issues/1357
Adds thirdweb RPC. I also tested confidential queries and they seem to work.
=> docs: Add thirdweb RPC

docs/develop/security.md
Closes #585 
Preview URL: https://deploy-preview-616--oasisprotocol-sapphire-paratime.netlify.app/build/sapphire/develop/security#gas-padding
=> docs: improve gas padding explanation
